### ISSUE TITLE
Fatal Error....

### ISSUE THREAD

**Issue by geogerar** [jamesdouble/JDMailBox#1]
Hi,

I try to run your example but i got the following error....
"fatal error: unexpectedly found nil while unwrapping an Optional value"
in exactly that instruction of your example --->  jdmailbox.maildelegate = self 

can you take a look and fix it?

Thank you in advance

George Gerardis

**Comment by jamesdouble** [comment]
Thanks for your feedback. I have found the problem in my example,
just the problem which I warn in this repository readme **"Notice"**.

Because simulator(ios 8.X) support opening MFComposeViewController, which simulator(ios 10.X) not support. so I forgot to add _"JDMailBoxComposeVC.canSendMail()"_ in my ViewController.
